### ISSUE TITLE
Error trying to send private message

### ISSUE THREAD

**Issue by ChristopheDeG** [mccrodp/message_private#24] opened 2017-06-19 09:18 UTC
Hi,

When trying to send a private message, I get the following error:

Type: message
Location: /message/add/private_message
InvalidArgumentException: Unable to get a value with a non-numeric delta in a list. in Drupal\Core\TypedData\Plugin\DataType\ItemList->get() (regel 98 van /home/dceh1/www/core/lib/Drupal/Core/TypedData/Plugin/DataType/ItemList.php).

Type: php
Location: /message/add/private_message
Drupal\Core\Entity\EntityStorageException: Unable to get a value with a non-numeric delta in a list. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (regel 777 van /home/dceh1/www/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

**Comment by mccrodp** [comment] 2017-06-20 08:54
Thanks for filing the bug Christophe. If you could submit a PR that would be really appreciated as I don't have much time for bug fixes on this at the moment.

**Comment by NewZeal** [comment] 2017-08-13 20:05
This is a duplicate of https://github.com/mccrodp/message_private/issues/18

**Closed as completed by NewZeal** 2017-08-13 20:05 UTC

**Comment by mccrodp** [comment] 2017-08-13 22:32
The other issue had less info than this one. I'll link it to here.
